#############################################################################
# Makefile for building: untitled3.app/Contents/MacOS/untitled3
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  DyTabView.pro
# Template: app
# Command: /Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile DyTabView.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang -I. -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuickWidgets.framework/Versions/5/Headers -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib
QMAKE         = /Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = untitled31.0.0
DISTDIR = /Users/tobyyi/Qt-Work-Space/yitb/QtDemo/untitled3/.tmp/untitled31.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib -framework QtQuickWidgets -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = tabview.qml \
		Mytab.qml \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resources.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/moc.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/uic.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/lex.prf \
		DyTabView.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = untitled3
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = untitled3.app/Contents/MacOS/untitled3

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d untitled3.app/Contents/MacOS/ || mkdir -p untitled3.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DyTabView.pro ../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resources.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/moc.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/uic.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/lex.prf \
		DyTabView.pro \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuickWidgets.framework/QtQuickWidgets.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile DyTabView.pro
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qdevice.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/device_config.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/unix.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/mac.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/macx.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/qconfig.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xlsx_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/default_post.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/qt.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/resources.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/moc.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/uic.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/yacc.prf:
../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/features/lex.prf:
DyTabView.pro:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuickWidgets.framework/QtQuickWidgets.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile DyTabView.pro

qmake_all: FORCE

untitled3.app/Contents/PkgInfo: 
	@test -d untitled3.app/Contents || mkdir -p untitled3.app/Contents
	@$(DEL_FILE) untitled3.app/Contents/PkgInfo
	@echo "APPL????" >untitled3.app/Contents/PkgInfo
untitled3.app/Contents/Resources/empty.lproj: 
	@test -d untitled3.app/Contents/Resources || mkdir -p untitled3.app/Contents/Resources
	@touch untitled3.app/Contents/Resources/empty.lproj
	
untitled3.app/Contents/Info.plist: 
	@test -d untitled3.app/Contents || mkdir -p untitled3.app/Contents
	@$(DEL_FILE) untitled3.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.dtuandui.myfirst.untitled3,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,untitled3,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >untitled3.app/Contents/Info.plist

all: Makefile \
		untitled3.app/Contents/PkgInfo \
		untitled3.app/Contents/Resources/empty.lproj \
		untitled3.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r untitled3.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		mainwindow.h
	/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/mkspecs/macx-clang -I/Users/tobyyi/Qt-Work-Space/yitb/QtDemo/untitled3 -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuickWidgets.framework/Headers -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuick.framework/Headers -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQml.framework/Headers -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Users/tobyyi/Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuickWidgets.framework/Versions/5/Headers/QQuickWidget \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtQuickWidgets.framework/Versions/5/Headers/qquickwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mainwindow.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDataStream \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatastream.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../../Qt-SDK-ALL/QtAndroidiOS/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

